services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=code_classroom
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=code_classroom_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
